version: "3"

services:
    frontend:
        build:
            context: ./frontend
        ports:
            - "3000:80"
        depends_on:
            - backend
        networks:
            - app-network

    backend:
        build:
            context: ./backend
        ports:
            - "3001:3001"
        depends_on:
            - db
        networks:
            - app-network
        environment:
            - DATABASE_URL=postgres://user:password@db:5432/mydb

    db:
        image: postgres:13
        restart: always
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: mydb
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - app-network

volumes:
    pgdata:

networks:
    app-network:
        driver: bridge
