version: "3"

services:
    nextjs:
        build:
            context: .
        ports:
            - "3000:3000"
        depends_on:
            - db
        networks:
            - app-network
        environment:
            - DATABASE_URL=postgres://user:password@db:5432/mydb
        volumes:
            - .:/app

    db:
        image: postgres:13
        restart: always
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: mydb
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - app-network

volumes:
    pgdata:

networks:
    app-network:
        driver: bridge
