// Auto-generated seed data for universities
const universities = [
	{ name: "Deakin University", location: "Australia" },
	{ name: "Queensland Uni. of Technology", location: "Australia" },
	{ name: "Macquarie University", location: "Australia" },
	{ name: "Uni. of Western Australia", location: "Australia" },
	{ name: "University of Queensland", location: "Australia" },
	{ name: "University of Melbourne", location: "Australia" },
	{ name: "University of Sydney", location: "Australia" },
	{ name: "University of New South Wales", location: "Australia" },
	{ name: "University of Adelaide", location: "Australia" },
	{ name: "Monash University", location: "Australia" },
	{ name: "Paris Lodron Universitt Salzburg", location: "Austria" },
	{ name: "Universit Libre de Bruxelles", location: "Belgium" },
	{ name: "University of Ottawa", location: "Canada" },
	{ name: "Dalhousie University", location: "Canada" },
	{ name: "University of Calgary", location: "Canada" },
	{ name: "University of British Columbia", location: "Canada" },
	{ name: "U of British Columbia Okanagan", location: "Canada" },
	{ name: "University of Toronto", location: "Canada" },
	{ name: "Simon Fraser University", location: "Canada" },
	{ name: "Queen's University", location: "Canada" },
	{ name: "McGill University", location: "Canada" },
	{ name: "Pontificia Univ.Catolica Chile", location: "Chile" },
	{ name: "Univ.of Nottingham Ningbo Campus", location: "China" },
	{ name: "Aarhus Universitet", location: "Denmark" },
	{ name: "University of Helsinki", location: "Finland" },
	{ name: "Universit Aix-Marseille", location: "France" },
	{ name: "Eberhard Karls Universitat Tubingen", location: "Germany" },
	{ name: "Johannes-Gutenberg-Universitat Mainz", location: "Germany" },
	{
		name: "National and Kapodistrian University of Athens",
		location: "Greece",
	},
	{ name: "University of Hong Kong", location: "Hong Kong" },
	{ name: "Chinese Univ of Hong Kong", location: "Hong Kong" },
	{
		name: "HKUST - Hong Kong University of Science and Technology",
		location: "Hong Kong",
	},
	{ name: "Sapienza University of Rome", location: "Italy" },
	{ name: "Keio University", location: "Japan" },
	{ name: "Waseda University", location: "Japan" },
	{ name: "Kyoto University", location: "Japan" },
	{ name: "Hitotsubashi University", location: "Japan" },
	{ name: "University of Tokyo", location: "Japan" },
	{ name: "Yonsei University", location: "Korea, Republic of" },
	{ name: "Korea University", location: "Korea, Republic of" },
	{ name: "Seoul National University", location: "Korea, Republic of" },
	{ name: "Uni of Nottingham Malaysia", location: "Malaysia" },
	{ name: "Tecnologico de Monterrey", location: "Mexico" },
	{ name: "Radboud Universiteit Nijmegen", location: "Netherlands" },
	{ name: "Universiteit van Amsterdam", location: "Netherlands" },
	{ name: "University of Auckland", location: "New Zealand" },
	{ name: "University of Otago", location: "New Zealand" },
	{ name: "Universidade de Lisboa", location: "Portugal" },
	{ name: "University of Bucharest", location: "Romania" },
	{ name: "Singapore Management University", location: "Singapore" },
	{ name: "National Univ.of Singapore", location: "Singapore" },
	{ name: "Nanyang Technological Univ.", location: "Singapore" },
	{ name: "Universidad Autonoma de Madrid", location: "Spain" },
	{ name: "Stockholms Universitet", location: "Sweden" },
	{ name: "Universite de Lausanne", location: "Switzerland" },
	{ name: "National Taiwan Normal Uni", location: "Taiwan" },
	{ name: "University of Vermont", location: "United States" },
	{ name: "Bentley University", location: "United States" },
	{ name: "State Univ. of New York Albany", location: "United States" },
	{ name: "University of California", location: "United States" },
	{ name: "Uni of Wisconsin Madison", location: "United States" },
	{ name: "University of Virginia", location: "United States" },
	{ name: "University of Texas at Austin", location: "United States" },
	{ name: "U.of North Carolina-Chapel Hill", location: "United States" },
	{ name: "University of Florida", location: "United States" },
	{ name: "University of Alabama", location: "United States" },
	{ name: "Radford University", location: "United States" },
	{ name: "Miami University OH", location: "United States" },
	{ name: "Uni of Massachusetts Amherst", location: "United States" },
	{ name: "University of Oklahoma", location: "United States" },
	{ name: "University of Miami, Florida", location: "United States" },
	{ name: "American University", location: "United States" },
	{ name: "University of Alaska Fairbanks", location: "United States" },
	{ name: "Boston College", location: "United States" },
	{ name: "University of Minnesota", location: "United States" },
	{ name: "University of Denver", location: "United States" },
];

module.exports = universities;
